"""TASK 2.1 — canonical data model for MAFAULDA signal recordings.

Schema definition only: no data ingestion, no windowing, no CSV parsing, no MAFAULDA
import happens here. Raw signal values are never stored in the database — `file_path`
is a reference to the source file on disk, per backlog TASK 2.1's own instruction.

Modeling note (discrepancy, documented rather than silently resolved): backlog's TASK
2.1 attributes this field set to "blueprint.md secțiunea 25", but section 25 is
actually "Reproducibility" (experiment/seed tracking) — unrelated to this model. The
real entity list (`datasets`, `signals`, `signal_windows`) is in blueprint.md section 22
("Database Strategy"), which names only three tables — there is no separate
"recordings" table. Backlog's "SignalRecord/Recording" is therefore modeled here as ONE
entity (table `signals`), not two; there is no blueprint-authoritative table to split
recording-level metadata (machine_id, operating_condition, label) from signal-level
metadata (sampling_rate, channel, file_path).

`SignalLabel` mirrors exactly the classes confirmed in
docs/dataset_audit/AUDIT_REPORT.md (TASK 1.5.9), sourced from
`app.datasets.mafaulda_parser.KNOWN_STATES` — never invented, never copied from
external MAFAULDA documentation. `UNKNOWN` is intentionally excluded: it is TASK
1.5.2's mapping-failure sentinel, not a physical signal state, and 0 recordings in the
real dataset ever produce it.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field
from sqlalchemy import CheckConstraint, ForeignKey, Integer, String
from sqlalchemy import Enum as SAEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.datasets.mafaulda_parser import KNOWN_STATES


class SignalLabel(str, Enum):
    NORMAL = "normal"
    IMBALANCE = "imbalance"
    HORIZONTAL_MISALIGNMENT = "horizontal-misalignment"
    VERTICAL_MISALIGNMENT = "vertical-misalignment"


assert {member.value for member in SignalLabel} == KNOWN_STATES, (
    "SignalLabel must mirror mafaulda_parser.KNOWN_STATES exactly — if this assertion "
    "fails, the audit-confirmed class set has changed and this enum needs updating."
)


class SignalRecord(BaseModel):
    """Pydantic validation/domain schema — see module docstring for why this covers
    what backlog calls both "Recording" and "SignalRecord"."""

    id: int | None = None
    dataset_id: int
    sampling_rate: float = Field(gt=0)
    # 8 channels (0-7) confirmed for every one of the 880 real files —
    # docs/dataset_audit/AUDIT_REPORT.md §5/§9 — not an arbitrary bound.
    channel: int = Field(ge=0, le=7)
    file_path: str
    # docs/dataset_audit/AUDIT_REPORT.md §7: no machine/session ID exists in the real
    # dataset — this is never populated with invented data by this task.
    machine_id: str | None = None
    # Severity sub-folder (e.g. "10g", "0.5mm") where the audit confirms one exists;
    # None for `normal`, which has no severity sub-folder (recording_mapping.md).
    operating_condition: str | None = None
    label: SignalLabel


class Dataset(Base):
    __tablename__ = "datasets"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String, nullable=False, unique=True)

    signals: Mapped[list["Signal"]] = relationship(back_populates="dataset")


class Signal(Base):
    __tablename__ = "signals"
    __table_args__ = (CheckConstraint("sampling_rate > 0", name="ck_signals_sampling_rate_positive"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    dataset_id: Mapped[int] = mapped_column(ForeignKey("datasets.id"), nullable=False)
    sampling_rate: Mapped[float] = mapped_column(nullable=False)
    channel: Mapped[int] = mapped_column(Integer, nullable=False)
    file_path: Mapped[str] = mapped_column(String, nullable=False)
    machine_id: Mapped[str | None] = mapped_column(String, nullable=True)
    operating_condition: Mapped[str | None] = mapped_column(String, nullable=True)
    label: Mapped[SignalLabel] = mapped_column(SAEnum(SignalLabel), nullable=False)

    dataset: Mapped["Dataset"] = relationship(back_populates="signals")
    windows: Mapped[list["SignalWindow"]] = relationship(back_populates="signal")


class SignalWindow(Base):
    """Schema only — no windows are generated by this task (see blueprint section 22's
    entity list and backlog TASK 2.1's explicit exclusion of windowing)."""

    __tablename__ = "signal_windows"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    signal_id: Mapped[int] = mapped_column(ForeignKey("signals.id"), nullable=False)
    start_sample: Mapped[int] = mapped_column(Integer, nullable=False)
    end_sample: Mapped[int] = mapped_column(Integer, nullable=False)

    signal: Mapped["Signal"] = relationship(back_populates="windows")
